# Generated by Django 3.1.3 on 2023-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230130_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='partial_grade',
            field=models.FloatField(default=1),
        ),
    ]
